version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest-armhf
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /home/dezed/proxy-manager/config.json:/app/config/production.json
      - /home/dezed/proxy-manager/data:/data
      - /home/dezed/proxy-manager/letsencrypt:/etc/letsencrypt
      - /home/dezed/proxy-manager/www:/var/www/html
    depends_on:
      - db
  db:
    image: yobasystems/alpine-maria:armhf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "dezed123"
      MYSQL_DATABASE: "nginxproxymanager"
      MYSQL_USER: "nginxproxymanager"
      MYSQL_PASSWORD: "dezed123"
    volumes:
      - /home/dezed/proxy-manager/mysql:/var/lib/mysql

{
  "database": {
    "engine": "mysql",
    "host": "db",
    "name": "nginxproxymanager",
    "user": "nginxproxymanager",
    "password": "dezed123",
    "port": 3306
  }
}